name: mzo
base: core18
version: "0.2.5"
summary: A command-line interface to your monzo account.
description: |
  This is a third-party, command-line tool which allows
  control over your Monzo bank account. Allows you to
  you balance, move money between pots, view transaction
  history, etc.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  mzo:
    command: bin/mzo
    plugs: [network, network-bind]

parts:
  mzo:
    plugin: python
    python-version: python3
    source: https://github.com/jamesstidard/Mzo-Cli/archive/v0.2.5.tar.gz
    source-checksum: sha256/6c40934df0b3146c7428dfe0c5d98b623fcf3f3ca9ec094d2bfdad2906f6f9ad
    requirements:
      - requirements.txt
