name: mzo
version: '0.0.1' # TODO: template
summary: A command-line interface to your monzo account.
description: |
  This is a third-party, command-line tool which allows
  control over your Monzo bank account. Allows you to
  you blance, move money between pots, view transaction
  history, etc.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

plugs:
  python3:
    interface: content
    content: python3
    target: python
    default-provider: python36-jamesh

apps:
  mzo:
    command: bin/mzo
    plugs:
      - python3

parts:
  mzo:
    plugin: dump
    source: .
    override-build: |
      # Create directory to serve as mount point for Python
      mkdir $SNAPCRAFT_PART_INSTALL/python
      python3 -V
      ls $SNAPCRAFT_PART_INSTALL/python
      pip install pipenv
      pipenv install
    prime:
      - python/