name: mzo
version: '0.0.1' # TODO: template
summary: A command-line interface to your monzo account.
description: |
  This is a third-party, command-line tool which allows
  control over your Monzo bank account. Allows you to
  you blance, move money between pots, view transaction
  history, etc.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  mzo:
    command: bin/mzo

parts:
  mzo:
    plugin: nil
    stage-packages:
      - python3.6
    source: .
    build: |
      python3.6 -V