name: mzo
version: '0.0.1' # TODO: template
summary: A command-line interface to your monzo account.
description: |
  This is a third-party, command-line tool which allows
  control over your Monzo bank account. Allows you to
  you blance, move money between pots, view transaction
  history, etc.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  mzo:
    command: /usr/local/bin/mzo
    plugs: [network, network-bind]

parts:
  python36:
    plugin: nil
    stage-packages:
      - make
      - zlib1g-dev
      - openssl
      - libssl-dev
      - libffi-dev
    source: https://www.python.org/ftp/python/3.6.5/Python-3.6.5.tar.xz
    source-checksum: md5/9f49654a4d6f733ff3284ab9d227e9fd
    override-build: |
      ./configure --enable-optimizations
      make
      sudo make install
  mzo:
    after: [python36]
    plugin: nil
    source: https://github.com/jamesstidard/Mzo-Cli/archive/v0.0.5.tar.gz # TODO: template
    source-checksum: sha256/ad70091661bc3bf920022b59423999d82c7f050338832f14c84a3044a431d48c # TODO: template
    override-build: |
      /usr/local/bin/python3 -m pip install --upgrade pip wheel setuptools pipenv
      pipenv lock --requirements > requirements.txt
      /usr/local/bin/python3 -m pip install -r requirements.txt
    prime:
      - /usr/local/bin/mzo
