name: mzo
base: core18
version: "0.2.4"
summary: A command-line interface to your monzo account.
description: |
  This is a third-party, command-line tool which allows
  control over your Monzo bank account. Allows you to
  you balance, move money between pots, view transaction
  history, etc.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  mzo:
    command: bin/mzo
    plugs: [network, network-bind]

parts:
  mzo:
    plugin: python
    python-version: python3
    source: https://github.com/jamesstidard/Mzo-Cli/archive/v0.2.4.tar.gz
    source-checksum: sha256/e4f483ae2c7756f07e6832175e84ef5864646f4a01f95f13ddfa44903328acc7
    stage-packages:
      - aioconsole==0.1.15
      - aiofiles==0.4.0
      - aiohttp==4.0.0a1
      - async-timeout==3.0.1
      - attrs==19.3.0
      - certifi==2019.11.28
      - cffi==1.14.0
      - chardet==3.0.4
      - click==7.0
      - fuzzywuzzy[speedup]==0.18.0
      - h11==0.8.1
      - h2==3.2.0
      - hpack==3.0.0
      - hstspreload==2020.2.15
      - httptools==0.1.1
      - httpx==0.9.3
      - hyperframe==5.2.0
      - idna==2.8
      - multidict==4.7.4
      - ordered-set==3.1.1
      - pycparser==2.19
      - pynacl==1.3.0
      - python-dateutil==2.8.1
      - python-levenshtein==0.12.0
      - rfc3986==1.3.2
      - sanic==19.12.2
      - six==1.14.0
      - sniffio==1.1.0
      - terminaltables==3.1.0
      - toml==0.10.0
      - typing-extensions==3.7.4.1
      - ujson==1.35
      - uvloop==0.14.0
      - websockets==8.1
      - yarl==1.4.2
