name: Docs
on:
  push:
    branches:
      - master
      - dev
    tags:
      - v*
    paths:
      - docs/**
env:
  RELEASE_NAME: ${{ github.ref }}
  PIPENV_VENV_IN_PROJECT: true
jobs:
  build-docs:
    name: Building Docs
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - id: creating_virtual_environment
        run: npm install
      - id: building_docs
        run: npm run docs:build
      - id: deploying_docs
        run: cp -R docs/.vuepress/dist ~/Desktop/output/${RELEASE_NAME#*/*/}
